# -*- coding: utf-8 -*-
"""04_변수와_자료형.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TXC5VGOZHLJdHCMDYn52ixbKpCxdhrXQ
"""

abc=12340
print(abc)

abc



abc*1/2

abc*1/4

abc*1/5

print(Ed)

print('Ed')

type(string)

type(string1)

string="string test 1"

type(string)

print("string test")

print('string test')

\'\''

# 안녕하세요''

# 안녕하세요 ''

string1=

string1="string tset 1"

string2='string test 2'

print(string1)
print(string2)

type(string1)

type(string2)

long_string1='''[삼중 작은따옴표를 사용한 예]

long_string1='''dkdkdk'''

long_string1

long_string1='asdngwoeijg'''qefjqeifq'''woahgwrg"""adbuewg"""askjdgh'

long_string1='''asdngwoeijg'''"""qefjqeifq"""'''woahgwrg'''"""adbuewg"""'''askjdgh'''

long_string1

string3='this is a "double" quotation test'

string3

string4="this is a 'single' quotation test"

string4

long_string1='''[삼중 작은따옴표를 사용한 예] 파이썬에는 삼중 따옴표로 여러 행의 문자열을 입력할 수 있습니다. 큰따옴표(")와 작은따옴표(')도 입력할 수 있습니다.'''

long_string1

ong_string1='''[삼중 작은따옴표를 사용한 예] 파이썬에는 삼중 따옴표로 여러 행의 문자열을 입력할 수 있습니다. "큰따옴표(")와 '작은따옴표(')도 입력할 수 있습니다.'''

long_string1

long_string1='''[삼중 작은따옴표를 사용한 예] 파이썬에는 삼중 따옴표로 여러 행의 문자열을 입력할 수 있습니다. "큰따옴표"와 \'작은따옴표\'도 입력할 수 있습니다.'''

long_string1

a='enjoy'
b='python!'
c=a+b
print(c)

print(a*3)

print(c*3)

space=' '

print(a+space+b)

sp=' '

sp

a+sp+b

(a+sp)*3

# 1번 학생의 국어, 영어, 수학, 과학 점수가 각각 90, 95, 85, 80
student1=[90,95,85,80]

type(student1)

student1[0]

student1[1]

student1[-1]

student1[1]=100

student1

myfriends=['james', 'robert','lisa', 'mary']

myfriends

myfriends[2]

myfriends[3]

myfriends[-1]

mixedlist=[0,2,3.14,'python', 'program', true, myfriends]

mixedlist=[0,2,3.14,'python', 'program', True, myfriends]

mixedlist

list_con1=[1,2,3,4]

list_con2=[5,6,7,8]
list_con=[list_con1+list_con2]

list_con

list_con=list_con1+list_con2

list_con

list_con=list_con1*3

list_con

list_data=[0,1,2,3,4,5,6,7,8,9]

list_data

list_data[0:3]

list_data[4:8]

list_data[:3]

list

list_data[7:]

list_data[::2]

list_data

del list_data[6]

list_data

list_data1=[1,2,3,4,5]

5 in list_data1

6 in list_data1

1 in list_data1

6 in list_data

'james' in myfriends

'mary' in myfriends

'lisa' in myfriends

'peter' in myfriends

myfriends.append('thomas')

mafriends

myfriends

myfriends.insert(1, 'paul')

myfriends

myfriends

myfriends.extend(['laura','betty'])

myfriends

tuple1=(1,2,3,4)

tuple1

type(tuple1)

tuple1[1]

tuple2=5,6,7,8

tuple2

type(tuple2)

tuple3=(9,)
tuple4=10,

tuple3
tuple4

tuple3

tuple5=1,2,3,4

tuple5[1]=5

del tuple5[1]

tuple6=('a','b','c','d','e','f')

tuple6

tuple6.index('c')

tuple7='a','a','a','b','c','d'

tuple7.count('a')

set1={1,2,3}

set1a={1,2,3,3}

set1

set1a

type(set1)

A={1,2,3,4,5}
B={4,5,6,7,8,9,10}

A.intersection(B)

A.difference(B)

A.union(B)

A&B

A-B

A|B

a=[1,2,3,4,5]

type(a)

b=tuple(a)

b

type(b)

c=set(a)

c

type(c)

list(b)

list(c)

set1a

t=[1,1,1,1,1]

t

set(t)

t=set(t)

t

type(t)

list(t)

t=[1,1,1,1,1]

q=set(t)

q

list(q)

list_con

list_con.index(3)

list_con[3]

del list_con[3]

list_con[3]

list_con

country_capital={"영국":"런던", "프랑스":"파리","스위스":"베른","호주":"멜버른","덴마크":"코펜하겐"}

country_capital

type(country_capital)

country_capital["영국"]

dict_data1={1:"버스",3:"비행기",4:"택시",5:"자전거"}

dict_data1[3]

dict_data2={1:10,2:20,3:30,4:40,5:50}

dict_data2

dict_data2[4]

dict_data3={"list_data1":[11,12,13]}, "list_data2":[21,22,23]}

dict_data3={"list_data1":[11,12,13], "list_data2":[21,22,23]}

dict_data3

dict_data3["list_data2"]

mixed_dict={1:10, 'dict_num':{1:10,2:20}, "dict_list_tuple":{"A":[11,12,13], "B":(21,22,23)}, "dict_string":"이것은 책입니다."}

mixed_dict

country_capital["독일"]="베를린"

country_capital

country_capital["호주"]="캔버라"

country_capital

del country_capital["덴마크"]

fruit_code={"사과":101, "배":102, "딸기":103, "포도":104, "바나나":105}

fruit_code.keys()

dict_keys

fruit_code.values()

fruit_code.items()

list(fruit_code.keys)

list(fruit_code.keys())

list(fruit_code.values())

list(fruit_code.items())

fruit_code

fruit_code2+{"오렌지":106,"수박":107}

fruit_code2={"오렌지":106,"수박":107}

fruit_code.update(fruit_code2)

fruit_code

fruit_code2.clear()

fruit_code2

type(fruit_code2)

